import { eCoil } from "./constants";

const mapAlarmErros: Record<number, string> = {
  [eCoil["({Link2}1@B29)"]]: "ALARME EMERGENCIA",
  [eCoil["({Link2}1@B30)"]]: "ALARME DE TEMPERATURA MAXIMA",
  [eCoil["({Link2}1@B31)"]]: "ALARME DE TEMPERTUR MINIMA",
  [eCoil["({Link2}1@B32)"]]: "ALARME DE PRESSAO MAXIMA",
  [eCoil["({Link2}1@B33)"]]: "ALARME DE PRESSAO MINIMA",
  [eCoil["({Link2}1@B34)"]]: "ALARME AQUECEDOR",
  [eCoil["({Link2}1@B35)"]]: "ALARME UMIDADE MAXIMA",
  [eCoil["({Link2}1@B36)"]]: "ALARME UMIDADE MINIMA",
  [eCoil["({Link2}1@B37)"]]: "ALARME CO2 MAXIMA",
  [eCoil["({Link2}1@B38)"]]: "ALARME PALHETA DE SEGURANÇA",
  [eCoil["({Link2}1@B39)"]]: "ALARME TERMOSTATO DE SEGURANÇA",
  [eCoil["({Link2}1@B40)"]]: "ALARME DR1",
  [eCoil["({Link2}1@B41)"]]: "ALARME DR2",
  [eCoil["({Link2}1@B42)"]]: "ALARME DR3",
  [eCoil["({Link2}1@B43)"]]: "ALARME DR4",
  [eCoil["({Link2}1@B44)"]]: "ALARME DR5",
  [eCoil["({Link2}1@B45)"]]: "ALARME GRUPOS EXAUSTORES",
  [eCoil["({Link2}1@B46)"]]: "ALARME PLACA EVAPORATIVA",
  [eCoil["({Link2}1@B47)"]]: "ALARME NEBOLIZADOR",
  [eCoil["({Link2}1@B48)"]]: "ALARME INLET",
  [eCoil["({Link2}1@B49)"]]: "ALARME CORTINA",
  [eCoil["({Link2}1@B50)"]]: "ALARME CIRCULADOR DE AR",
  [eCoil["({Link2}1@B51)"]]: "ALARME COMEDOURO",
  [eCoil["({Link2}1@B52)"]]: "ALARME SILO",
  [eCoil["({Link2}1@B53)"]]: "ALARME FALTA ENERGIA",
  [eCoil["({Link2}1@B54)"]]: "ALARME SENSOR UMIDADE",
  [eCoil["({Link2}1@B55)"]]: "ALARME SENSOR PRESSAO",
  [eCoil["({Link2}1@B56)"]]: "ALARME SENSOR CO2",
  [eCoil["({Link2}1@B57)"]]: "ALARME SENSOR TEMPERATURA 1",
  [eCoil["({Link2}1@B58)"]]: "ALARME SENSOR TEMPERATURA 2",
  [eCoil["({Link2}1@B59)"]]: "ALARME SENSOR TEMPERATURA 3",
  [eCoil["({Link2}1@B60)"]]: "ALARME SENSOR TEMPERATURA 4",
  [eCoil["({Link2}1@B61)"]]: "ALARME SENSOR TEMPERATURA 5",
};

export { mapAlarmErros };
